-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["greekColumn"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   74, -137.5  ,  79, -132.5  ,  72, -85.5  ,  44, -77.5  ,  33, -133.5  ,  39, -139.5  ,  45, -142.5  ,  61, -143.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -84, -103.5  ,  -85, -114.5  ,  -82, -126.5  ,  -42, -77.5  ,  -59, -78.5  ,  -69, -82.5  ,  -78, -90.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   80, -92.5  ,  74, -85.5  ,  72, -85.5  ,  79, -132.5  ,  84, -123.5  ,  85, -104.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   60, -78.5  ,  44, -77.5  ,  72, -85.5  ,  66, -80.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -32, -133.5  ,  -79, -129.5  ,  -79, -131.5  ,  -69, -140.5  ,  -61, -143.5  ,  -48, -143.5  ,  -40, -140.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -42, -77.5  ,  50, -67.5  ,  -48, -67.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -82, -126.5  ,  -79, -129.5  ,  -32, -133.5  ,  44, -75.5  ,  50, -67.5  ,  -42, -77.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1, -1241.5  ,  -1, -1238.5  ,  -29, -1238.5  ,  -29, -1241.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   30, -1241.5  ,  30, -1238.5  ,  1, -1238.5  ,  1, -1241.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -32, -133.5  ,  33, -133.5  ,  44, -77.5  ,  44, -75.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -32, -133.5  ,  -32, -1238.5  ,  33, -1238.5  ,  33, -133.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -48, 66.5  ,  50, 66.5  ,  -44, 72.5  ,  -47, 70.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   47, 70.5  ,  50, 66.5  ,  50, 68.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   78, 133.5  ,  69, 140.5  ,  64, 142.5  ,  33, 133.5  ,  43, 77.5  ,  83, 97.5  ,  85, 104.5  ,  85, 119.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -56, 77.5  ,  -42, 77.5  ,  -32, 133.5  ,  -58, 143.5  ,  -85, 113.5  ,  -84, 102.5  ,  -78, 90.5  ,  -68, 81.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -78, 132.5  ,  -83, 123.5  ,  -85, 113.5  ,  -58, 143.5  ,  -70, 139.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   73, 84.5  ,  79, 90.5  ,  83, 97.5  ,  43, 77.5  ,  61, 78.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -50, 143.5  ,  -58, 143.5  ,  -32, 133.5  ,  -39, 139.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   38, 138.5  ,  33, 133.5  ,  64, 142.5  ,  46, 142.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -29, 1241.5  ,  -29, 1238.5  ,  -1, 1238.5  ,  -1, 1241.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1, 1241.5  ,  1, 1238.5  ,  30, 1238.5  ,  30, 1241.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   50, 66.5  ,  -42, 77.5  ,  -44, 72.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   50, 66.5  ,  47, 70.5  ,  -32, 133.5  ,  -42, 77.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   43, 77.5  ,  -32, 133.5  ,  47, 70.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   33, 133.5  ,  -32, 133.5  ,  43, 77.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   33, 133.5  ,  30, 1238.5  ,  -32, 1238.5  ,  -32, 133.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   30, 1238.5  ,  33, 133.5  ,  33, 1238.5  }
                    }
                    
                    
                    
		}
		
		, 
		["greekColumn2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   43, -100.5  ,  33, -110.5  ,  43, -110.5  ,  46, -108.5  ,  46, -101.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43, -110.5  ,  -32, -110.5  ,  -44, -100.5  ,  -46, -101.5  ,  -46, -108.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   48, -89.5  ,  -48, -89.5  ,  -44, -95.5  ,  43, -95.5  ,  47, -92.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -52, -67.5  ,  -52, -89.5  ,  52, -89.5  ,  52, -67.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -44, -95.5  ,  -48, -89.5  ,  -48, -91.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   43, -95.5  ,  -44, -95.5  ,  -44, -100.5  ,  -32, -110.5  ,  33, -110.5  ,  43, -100.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   33, -1244.5  ,  33, -110.5  ,  -32, -110.5  ,  -32, -1244.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -44, 93.5  ,  43, 94.5  ,  43, 99.5  ,  33, 108.5  ,  -32, 108.5  ,  -46, 107.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   33, 108.5  ,  43, 99.5  ,  46, 100.5  ,  46, 107.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -49, 87.5  ,  49, 87.5  ,  43, 94.5  ,  -44, 93.5  ,  -47, 91.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   52, 65.5  ,  52, 87.5  ,  -52, 87.5  ,  -52, 65.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -32, 1243.5  ,  -32, 108.5  ,  33, 108.5  ,  33, 1243.5  }
                    }
                    
                    
                    
		}
		
		, 
		["bottomColumn"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -58.5, -742.5  ,  69.5, -750.5  ,  -48.5, -733.5  ,  -58.5, -733.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -37.5, -696.5  ,  -32.5, -692.5  ,  -39.5, -692.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   32.5, -692.5  ,  37.5, -696.5  ,  39.5, -692.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -48.5, -733.5  ,  69.5, -750.5  ,  -43.5, -724.5  ,  -49.5, -725.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   48.5, -733.5  ,  57.5, -742.5  ,  59.5, -741.5  ,  58.5, -733.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   57.5, -742.5  ,  69.5, -750.5  ,  69.5, -742.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -70.5, -749.5  ,  -68.5, -751.5  ,  69.5, -750.5  ,  -58.5, -742.5  ,  -69.5, -742.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, -696.5  ,  39.5, -699.5  ,  39.5, -697.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -44.5, -706.5  ,  -42.5, -707.5  ,  -40.5, -699.5  ,  -44.5, -700.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   40.5, -713.5  ,  -32.5, -692.5  ,  43.5, -724.5  ,  44.5, -718.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43.5, -724.5  ,  69.5, -750.5  ,  -40.5, -712.5  ,  -44.5, -717.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   39.5, -699.5  ,  40.5, -710.5  ,  44.5, -705.5  ,  44.5, -701.5  ,  42.5, -699.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   43.5, -724.5  ,  48.5, -733.5  ,  49.5, -726.5  ,  47.5, -724.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -40.5, -712.5  ,  69.5, -750.5  ,  57.5, -742.5  ,  -32.5, -692.5  ,  -37.5, -696.5  ,  -40.5, -699.5  ,  -42.5, -707.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, -696.5  ,  32.5, -692.5  ,  -32.5, -692.5  ,  40.5, -713.5  ,  40.5, -710.5  ,  39.5, -699.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -32.5, 751.5  ,  -32.5, -692.5  ,  32.5, -692.5  ,  32.5, 751.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -32.5, -692.5  ,  48.5, -733.5  ,  43.5, -724.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -32.5, -692.5  ,  57.5, -742.5  ,  48.5, -733.5  }
                    }
                    
                    
                    
        }
		
		, 
		["corn"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -16.5, -60  ,  16.5, -60  ,  -22.5, -52  ,  -24.5, -58  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   23.5, -53  ,  -38.5, -31  ,  -22.5, -52  ,  16.5, -60  ,  24.5, -58  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -22.5, -52  ,  -38.5, -31  ,  -38.5, -44  ,  -36.5, -49  ,  -30.5, -53  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   36.5, -49  ,  38.5, -44  ,  38.5, -31  ,  23.5, -53  ,  30.5, -53  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -21.5, 50  ,  -14.5, 49  ,  13.5, 49  ,  24.5, 51  ,  26.5, 60  ,  -25.5, 60  ,  -24.5, 52  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   55.5, -1  ,  50.5, 12  ,  43.5, 20  ,  38.5, -31  ,  47.5, -26  ,  54.5, -16  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   26.5, 60  ,  24.5, 51  ,  26.5, 53  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -37.5, 29  ,  -37.5, 27  ,  36.5, 28  ,  28.5, 36  ,  13.5, 49  ,  -14.5, 49  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -50.5, -23  ,  -38.5, -31  ,  43.5, 20  ,  36.5, 28  ,  -43.5, 20  ,  -50.5, 12  ,  -55.5, 0  ,  -55.5, -14  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   43.5, 20  ,  -38.5, -31  ,  23.5, -53  ,  38.5, -31  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43.5, 20  ,  36.5, 28  ,  -37.5, 27  ,  -43.5, 22  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   36.5, 28  ,  43.5, 20  ,  43.5, 22  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   30.5, 36  ,  28.5, 36  ,  36.5, 28  ,  36.5, 30  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   13.5, 49  ,  28.5, 36  ,  20.5, 45  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -38.5, -31  ,  -50.5, -23  ,  -46.5, -27  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

