-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["single_bird"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -40, 16.5  ,  -37, 15.5  ,  -39, 18.5  ,  -41, 18.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -21, 9.5  ,  -18, 9.5  ,  -20, 11.5  ,  -23, 11.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   40, 3.5  ,  43, -0.5  ,  46, -0.5  ,  48, 3.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -40, 8.5  ,  -33, 12.5  ,  -35, 15.5  ,  -42, 15.5  ,  -43, 11.5  ,  -43, 9.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -40, -11.5  ,  -39, -8.5  ,  -41, -11.5  ,  -41, -13.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -46, 13.5  ,  -43, 11.5  ,  -42, 15.5  ,  -45, 18.5  ,  -47, 18.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -30, -7.5  ,  -33, -2.5  ,  -39, -8.5  ,  -40, -11.5  ,  -34, -11.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -12, 9.5  ,  -2, -11.5  ,  7, -12.5  ,  3, 14.5  ,  -2, 15.5  ,  -8, 15.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   40, 3.5  ,  37, 5.5  ,  30, 6.5  ,  29, -6.5  ,  41, -3.5  ,  43, -0.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -42, 15.5  ,  -37, 15.5  ,  -40, 16.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -40, 8.5  ,  -40, 5.5  ,  -32, 0.5  ,  -29, 10.5  ,  -33, 12.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -50, -12.5  ,  -41, -11.5  ,  -44, -10.5  ,  -50, -10.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -32, 0.5  ,  -24, -5.5  ,  -13, -5.5  ,  -21, 9.5  ,  -29, 10.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   22, 12.5  ,  14, 15.5  ,  3, 14.5  ,  17, -9.5  ,  24, -8.5  ,  29, -6.5  ,  30, 6.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3, 14.5  ,  7, -12.5  ,  17, -9.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -41, -11.5  ,  -39, -8.5  ,  -44, -10.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -24, -5.5  ,  -32, 0.5  ,  -33, -2.5  ,  -30, -7.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -6, -9.5  ,  -3, -9.5  ,  -12, 9.5  ,  -21, 9.5  ,  -13, -5.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -12, 9.5  ,  -10, 12.5  ,  -11, 11.5  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

